import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
        <title>BSP</title>
        <meta
          name="description"
          content="Découvrez les meilleures photos de sports du monde entier sur Best Sport Picture. Parcourez notre collection exceptionnelle d'images captivantes de sports tels que la boxe, le hockey, le basket-ball, le sprint, le tennis et bien plus encore. Explorez la beauté, la passion et l'action du monde du sport à travers nos clichés uniques."
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
